### ISSUE TITLE
Make 1.2.0 release/tag

### ISSUE THREAD

**Issue by grempa** [georgringer/news_redirect_slug_change#4]
Would be great to have a new release. 
Since the most current version via Packagist is the `1.1.0`, newer comits like the [TCA one](https://github.com/georgringer/news_redirect_slug_change/commit/bf8b152feb53db6e974b1351d8faf027945f6d28), are not "live" - which would be wonderful. ;)

**Comment by georgringer** [comment]
https://github.com/georgringer/news_redirect_slug_change/releases/tag/1.2.0
